### PR TITLE
Small Jupyter notebook Docker

### PR DESCRIPTION
**Pull request by Gilles86**
Hi guys,

This is such great work! Nighres is gonna make my life a lot easier. Thanks a bunch. 

I had to fight with Linux for a small day to get it to work though. Maybe it's nice to include a small Docker container with some minimal functionality?

### CODE REVIEW

**Comment by steelec** [comment]
Excellent, great add for usability and testing!

**Comment by juhuntenburg** [comment]
Supercool, thanks @Gilles86! Currently travelling but definitely will try this out once I have a little time.

We are also trying to make the standard installation easier... but even if we manage eventually, this is definitely extremely useful!

**Comment by juhuntenburg** [comment]
Actually, when I follow your instructions it builds the docker image fine, but when I try the run command I get the following error:

`[FATAL] Executing child process '-p' failed: 'No such file or directory'`

Any idea why?

**Comment by Gilles86** [comment]
@juhuntenburg: whoopsie! 

Yes, I know why. It should be:

`docker run --rm -p 8888:8888 nighres`

(instead of docker run --rm nighres -p 8888:8888)

**Pull request merged**
