### PR TITLE
Add a github workflow for testing build

### PR DESCRIPTION
**Pull request by gdevenyi**
Depends on #170

### CODE REVIEW

**Comment by gdevenyi** [comment]
Ideally this will be followed up with workflows which exercise each of the examples. I'd like to figure out how to store/use the resulting package.

**Comment by gdevenyi** [comment]
These workflows can also be used to generate proper complete downloadable wheels eventually, particularly if we setup an ubuntu environment with all the dependencies and build in that.

**Comment by piloubazin** [comment]
we're using Travis for testing the build; how is this different (or better)?

**Comment by gdevenyi** [comment]
Did it catch that the build was broken as per #166 ?

**Comment by gdevenyi** [comment]
You may be interested to see that travis-ci.org was shut down, and your CI hasn't been running for 10 months:
image

Github actions is of course the local-github branded product which does the same thing, but with more features, more free for academics, and is maintained.

**Comment by piloubazin** [comment]
I see.. the issue of multiple developers, I didn't get the update on Travis changing. Sounds like the github version is a better option going forward then?

**Comment by gdevenyi** [comment]
> Sounds like the github version is a better option going forward then?

I think it's a better implementation, having previously used both Circle and Travis.

**Comment by gdevenyi** [comment]
The repo needs actions enabled before this PR can be live-tested for errors.

**Comment by gdevenyi** [comment]
Hurrah it worked first time 🎉

**Comment by piloubazin** [comment]
Great!! Thanks for setting this up :)

**Pull request merged**
