### PR TITLE
Fix/filter

### PR DESCRIPTION
**Pull request by juhuntenburg**
Integrating filtering module and some small fixes for bandpass filtering. 

Not functional though, filtering returns straight line

### CODE REVIEW

**Comment by steelec** [comment]
I think the issue that you are running into is related to memory. It works on my machine, but causes a huge spike in memory usage (up to ~10 GB) that froze me out unless I had freed up more mem. Looking over the code now to see if I can reduce the mem usage, but it seems to work in principle (i.e., I get a full timeseries back rather than just the mean)

**Comment by steelec** [comment]
Looked into it, seems to be the fft.fft and the real conversion that are filling the memory. Didn't find much about memory usage for them, but the np.fft is pretty fast in comparison to scipy's implementation (https://stackoverflow.com/questions/6363154/what-is-the-difference-between-numpy-fft-and-scipy-fftpack). np.repeat could be replaced with the use of np.newaxis, but there is no difference to memory so there isn't much point :-).

**Comment by juhuntenburg** [comment]
I rebased this locally, could theoretically be merged but I haven't tested it again and got the weird results last time (see above), which might be due to running out of memory according to @steelec. If you want to try out the changes in this branch and possibly amend, you can do in your local repo:

```
git checkout -b juhuntenburg-fix/filter master
git pull https://github.com/juhuntenburg/nighres.git fix/filter
```

**Comment by piloubazin** [comment]
Tested, it returns something sensible (it may not be a very good filter, but that's beside the point)

**Pull request merged**
