### PR TITLE
Switch to using git submodules to maintain version stability

### LINKED ISSUE #167: submodules should be use to allow for proper versioning
The build.sh is pretty hairy, with some particular pieces which are very anti-reproducibility:

https://github.com/nighres/nighres/blob/master/build.sh#L46-L60

This git pull means that every single installation of nighres is likely to have different out-of-sync HEADS for this repo, cbs-tools, and imcn-imaging

The standard way to include projects in other projects is with submodules see https://gist.github.com/gitaarik/8735255 for a quick rundown.

This will allow a fixed version of this repo to correspond to specific versions of the included code as well.

### PR DESCRIPTION
**Pull request by gdevenyi**
The current HEAD of each submodule is now part of the commit stream of this repo.

To update the dependencies submodules, do
`git submodule update --remote --merge` to get latest versions.

To update to specific commit on a submodule
```
$ cd submodule_dir
$ git checkout <tag or HASH>
$ git add .
$ git commit
```

Fixes #167

### CODE REVIEW

**Comment by piloubazin** [comment]
Looking at the link you sent and the changes you made, it seems to me submodules mostly add a layer of complexity without bringing anything else. I do understand that it allows to make the nighres and integrated libraries work more independently, but I'm not sure we actually want that (instances where a base library is broken are rare, and easily fixed too).

**Comment by gdevenyi** [comment]
Related to this, a workflow which runs on updates to the main code, and submodules, as per https://github.com/nighres/nighres/pull/172#issuecomment-1030290963 would also have helped avoid #166

**Comment by gdevenyi** [comment]
> but I'm not sure we actually want that (instances where a base library is broken are rare, and easily fixed too).

My major concern from an open science reproducibility perspective is that the current build/install process can result in every user having a "different" version of nighres and the underlying dependencies, this versions should instead be controlled to avoid this.

**Comment by piloubazin** [comment]
I do see your point; I just don't find the "solution" any better, as it requires to choose between fully frozen repos and continuous updates. I'd rather make release branches for the libraries at release time, so everything is synchronized and searchable. I'll look into it.

**Pull request closed without merging**
