### PR TITLE
moving docker related files in a separate directory

### PR DESCRIPTION
**Pull request by juhuntenburg**
@Gilles86 This seems to work for me, any reason to not do it?

### CODE REVIEW

**Comment by Gilles86** [comment]
I sort of copied this from [nipype](https://github.com/nipy/nipype/blob/master/Dockerfile) and [fmriprep](https://github.com/poldracklab/fmriprep/blob/master/Dockerfile), where they put the Dockerfile in the root folder of the project.

I realize now that they probably do so because when you build a Dockerfile, everything in the folder of that Dockerfile gets added to the 'build environment' and can be copied into the Docker environment. In that way, you can directly copy the source code of the project into the Docker container (see, e.g., [here](https://github.com/nipy/nipype/blob/8ce4b9bab071e6d4de96cd25d2e2a4050200c511/Dockerfile#L94) and [here](https://github.com/poldracklab/fmriprep/blob/4869d07612c6fe63a55079cf8c9c5d69f0e08361/Dockerfile#L164])).

The current nighres file downloads the nighres source code 'twice' ([here](https://github.com/juhuntenburg/nighres/blob/08921d6d77893840c155e9a0b0eb15906f9f2b00/Dockerfile#L15)]. That maybe is a bit less elegant than the nipype/fmriprep solution. I can live with it, but another option would be to move the Dockerfile back to the root directory and replace

`RUN cd /home/neuro && git clone https://github.com/nighres/nighres && cd nighres && ./build.sh && pip install .
`
by
`COPY nighres /home/neuro
RUN cd /home/neuro/nighres && ./build.sh && pip install .`

What do you think?

**Comment by piloubazin** [comment]
I concur with Julia: optional configuration stuff for Docker or other additional tool (like e.g. the documentation) should go in their own subfolder.

**Comment by Gilles86** [comment]
@piloubazin: I completely agree about configuration files. 

The only exception might be the Dockerfile itself I think. If you do not put it in the root, but in a deeper folder, you have to re-download (and store) the entire 1.5GB git nighres repository every time you build the Docker container (because then it has no access to the version on the host OS).

**Comment by juhuntenburg** [comment]
@Gilles86 sounds good, config files in docker subfolder and Dockerfile in root so we don't have to download twice. Also, I haven't played much with Docker, is there any way to get around running the build script? Like, could we pre-make a docker image on which the build script has been run and people just grab that instead of the plain ubuntu image? or is that not how it works? 
More curiosity, what you suggest seems like a good option for now!

**Comment by Gilles86** [comment]
@juhuntenburg: no I think there is no way around this. As far as I understand, this is due to the difference between a container system like Docker, which is 'just' a layer on your host OS, vs a full-fledged virtual machine that basically simulates an entire computer (https://stackoverflow.com/questions/16047306/how-is-docker-different-from-a-normal-virtual-machine).

I implemented a Dockerfile that re-uses the already downloaded data in this branch here:
https://github.com/Gilles86/nighres/tree/docker_dir

**Comment by juhuntenburg** [comment]
@Gilles86 Alright cool, thanks for explanation! Want to just make a PR from your branch then?

**Comment by Gilles86** [comment]
Yup.
https://github.com/nighres/nighres/pull/74

**Pull request merged**
